//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azurite.Store.Resources.Views.Home.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувай сега.
        /// </summary>
        public static string CaoruselBtnCaption2 {
            get {
                return ResourceManager.GetString("CaoruselBtnCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувай сега.
        /// </summary>
        public static string CarouselBtnCaption1 {
            get {
                return ResourceManager.GetString("CarouselBtnCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пазарувай сега.
        /// </summary>
        public static string CarouselBtnCaption3 {
            get {
                return ResourceManager.GetString("CarouselBtnCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Minimal.
        /// </summary>
        public static string CarouselCaption1 {
            get {
                return ResourceManager.GetString("CarouselCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Minimal.
        /// </summary>
        public static string CarouselCaption2 {
            get {
                return ResourceManager.GetString("CarouselCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Minimal.
        /// </summary>
        public static string CarouselCaption3 {
            get {
                return ResourceManager.GetString("CarouselCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Златна Колекция.
        /// </summary>
        public static string CarouselSubCaption1 {
            get {
                return ResourceManager.GetString("CarouselSubCaption1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Златна Колекция.
        /// </summary>
        public static string CarouselSubCaption2 {
            get {
                return ResourceManager.GetString("CarouselSubCaption2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Златна Колекция.
        /// </summary>
        public static string CarouselSubCaption3 {
            get {
                return ResourceManager.GetString("CarouselSubCaption3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Продукти.
        /// </summary>
        public static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Промоции.
        /// </summary>
        public static string Promotions {
            get {
                return ResourceManager.GetString("Promotions", resourceCulture);
            }
        }
    }
}
