//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Azurite.CDN.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityKeys
    {
        public int Id { get; set; }
        public System.Guid Key { get; set; }
        public string Name { get; set; }
    }
}
