//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewRes {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SCCheckout {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SCCheckout() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Azurite.Store.Resources.Views.ShoppingCart.SCCheckout", typeof(SCCheckout).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще заплатиш на куриера, при доставката на поръчката. За вземане от офис на куриер ще заплатиш в избрания от теб офис..
        /// </summary>
        public static string FeildsetFieldNote {
            get {
                return ResourceManager.GetString("FeildsetFieldNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наложен платеж.
        /// </summary>
        public static string FieldsetFieldLabel {
            get {
                return ResourceManager.GetString("FieldsetFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лични данни.
        /// </summary>
        public static string FieldsetHeader1 {
            get {
                return ResourceManager.GetString("FieldsetHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес.
        /// </summary>
        public static string FieldsetHeader2 {
            get {
                return ResourceManager.GetString("FieldsetHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фирмени данни.
        /// </summary>
        public static string FieldsetHeader3 {
            get {
                return ResourceManager.GetString("FieldsetHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допълнителна информация.
        /// </summary>
        public static string FieldsetHeader4 {
            get {
                return ResourceManager.GetString("FieldsetHeader4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиентски данни.
        /// </summary>
        public static string FieldsetLegend1 {
            get {
                return ResourceManager.GetString("FieldsetLegend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доставка &amp; Плащане.
        /// </summary>
        public static string FieldsetLegend2 {
            get {
                return ResourceManager.GetString("FieldsetLegend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация за поръчката.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
